In [2]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

In [1]:
import pandas as pd
hoho = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/hoho_RR_final.csv")

panda1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Panda_final.csv")
panda2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Panda_Kakao_final.csv")

hk1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/HK_mara_final.csv")
hk2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/HK_Kakao_final.csv")

hj1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/hanjung_final.csv")
hj2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Hanjung_Kakao_final.csv")

In [4]:
panda=pd.concat([panda1,panda2],ignore_index=True)
hk=pd.concat([hk1,hk2],ignore_index=True)
hj=pd.concat([hj1,hj2],ignore_index=True)

In [ ]:
hj

,Unnamed: 0.1,Unnamed: 0,0,1,2,senti
0,0,0,대전에 새로 이사 와서 찾은 집 근처 맛집!!! 첫번째!!! 마라탕과 꿔바로우 현...,A restaurant near my new house in Daejeon!!! F...,6.0,pos
1,1,1,맛있긴합니다만ㅠㅠ야채선택해서(숙주),It's deliciousI'll pick the host. (host),0.0,neutral
2,2,2,정말 맛있습니다^^~,It's really good^^~,3.0,pos
3,3,3,친구랑 갔는데 가성비 좋고 깨끗하고 좋았어요 친구는 맛있었다고 했지만 제 취향은 아...,I went with my friend and it was good and clea...,12.0,pos
4,4,4,양고기추가에 기름기가 없고 너무 좋아요,It's really good because it's not greasy,3.0,pos
...,...,...,...,...,...,...
138,2,2,맛있고 위생적이고 친절해요 오류동에 있을 때부터 자주 갔는데 넓어져서 더 만족스러웠어요,"It's delicious, hygienic, and kind I went ther...",7.0,pos
139,3,3,.,.,0.0,neutral
140,4,4,맛 최고 최고~ 아줌마가 친절하세요^^,The taste is the best! The lady is kind^^,5.0,pos
141,5,5,맛나용ㅎㅎ,It's delicious,3.0,pos
142,6,6,존맛탱!!,It's so delicious!!,3.0,pos

In [ ]:
panda.head()

,Unnamed: 0.1,Unnamed: 0,0,1,2,senti
0,0,0,은행동. 판다마라탕. 다들 식성이 달라서 가지각색. 두부탕. 감자탕. 해물탕. ㅋ...,Eunhaeng-dong. Panda malatang. Everyone has di...,4.0,pos
1,1,1,못 기다리겠다 일단 한 입만 먹고 나머지 사진은 나중에 찍자,I can't wait. Let's take a bite and take the r...,0.0,neutral
2,2,2,진짜 맛있게 잘먹었습니다 여기 있는마라탕 항상 한그롯 뚝딱^^ 오늘 친구랑 같이와서...,I really enjoyed the food This malatang is alw...,6.0,pos
3,3,3,시험끝나고 먹으러왔어요~!~! 시험점수 날아가라~~~마라먹고 나라가라~~~~~ 마싯어요💜,I'm here to eat after the exam! Fly away your ...,0.0,neutral
4,4,4,친구랑 주기적으로 먹으러 오는 은행동 맛집이에용 개인적으로 먹어 본 마라탕 중에 제...,The restaurant in Eunhaeng-dong that I regular...,4.0,pos

In [5]:
DF_panda = panda[panda.senti != 'neutral']
DF_hk = hk[hk.senti != 'neutral']
DF_hj = hj[hj.senti != 'neutral']
mara_df=pd.concat([DF_panda,DF_hk,DF_hj],ignore_index=True)
df_hoho= hoho[hoho.senti != 'neutral']

In [ ]:
mara_df.head()

,Unnamed: 0.1,Unnamed: 0,0,1,2,senti
0,0,0,은행동. 판다마라탕. 다들 식성이 달라서 가지각색. 두부탕. 감자탕. 해물탕. ㅋ...,Eunhaeng-dong. Panda malatang. Everyone has di...,4.0,pos
1,2,2,진짜 맛있게 잘먹었습니다 여기 있는마라탕 항상 한그롯 뚝딱^^ 오늘 친구랑 같이와서...,I really enjoyed the food This malatang is alw...,6.0,pos
2,4,4,친구랑 주기적으로 먹으러 오는 은행동 맛집이에용 개인적으로 먹어 본 마라탕 중에 제...,The restaurant in Eunhaeng-dong that I regular...,4.0,pos
3,5,5,가게가 2층에 있는데 깔끔하고 분위기도 좋아요\n고기 서비스 이벤트도 하고 있어서 ...,The store is on the second floor and it's neat...,3.0,pos
4,6,6,은행동 판다마라탕 아이들이 좋아해서 같이 먹어봣어요 먹을만하네요 맛잇게 먹엇어요,Panda Malatang in Eunhaeng-dong. The kids like...,2.0,pos

In [6]:
#이상치 분석 

def get_outlier(df=None, column=None, weight=1.5):
  # target 값과 상관관계가 높은 열을 우선적으로 진행
  quantile_25 = np.percentile(df[column].values, 25)
  quantile_75 = np.percentile(df[column].values, 75)

  IQR = quantile_75 - quantile_25
  IQR_weight = IQR*weight
  
  lowest = quantile_25 - IQR_weight
  highest = quantile_75 + IQR_weight
  
  # outlier_idx = df[column][ (df[column] < lowest) | (df[column] > highest) ].index
  return lowest,highest

# 함수 사용해서 이상치 값 삭제
low, high= get_outlier(df=mara_df, column='2', weight=1.5)

In [7]:
new_score=[]
for row in hoho['2']:
  if row >high:
    new_score.append(high)
  elif row < low:
    new_score.append(low)
  else:
    new_score.append(row)

hoho['score']=new_score

In [ ]:
for df in [DF_panda,DF_hj,DF_hk]:
  new_score=[]
  for row in df['2']:
    if row >high:
      new_score.append(high)
    elif row < low:
      new_score.append(low)
    else:
      new_score.append(row)

  df['score']=new_score

In [ ]:
mara_df=pd.concat([DF_panda,DF_hk,DF_hj],ignore_index=True)
mara_df.head()

,Unnamed: 0.1,Unnamed: 0,0,1,2,senti,score
0,0,0,은행동. 판다마라탕. 다들 식성이 달라서 가지각색. 두부탕. 감자탕. 해물탕. ㅋ...,Eunhaeng-dong. Panda malatang. Everyone has di...,4.0,pos,4.0
1,2,2,진짜 맛있게 잘먹었습니다 여기 있는마라탕 항상 한그롯 뚝딱^^ 오늘 친구랑 같이와서...,I really enjoyed the food This malatang is alw...,6.0,pos,6.0
2,4,4,친구랑 주기적으로 먹으러 오는 은행동 맛집이에용 개인적으로 먹어 본 마라탕 중에 제...,The restaurant in Eunhaeng-dong that I regular...,4.0,pos,4.0
3,5,5,가게가 2층에 있는데 깔끔하고 분위기도 좋아요\n고기 서비스 이벤트도 하고 있어서 ...,The store is on the second floor and it's neat...,3.0,pos,3.0
4,6,6,은행동 판다마라탕 아이들이 좋아해서 같이 먹어봣어요 먹을만하네요 맛잇게 먹엇어요,Panda Malatang in Eunhaeng-dong. The kids like...,2.0,pos,2.0

In [ ]:
scaler =MinMaxScaler()
mara_arr=np.array(mara_df['score'])
mara_arr=mara_arr.reshape(-1,1)
scaler.fit(mara_arr)

MinMaxScaler()

In [8]:
scaler =MinMaxScaler()
hoho_arr=np.array(hoho['score'])
hoho_arr=hoho_arr.reshape(-1,1)
scaler.fit(hoho_arr)

MinMaxScaler()

In [ ]:
panda_arr=np.array(DF_panda['score'])
hk_arr=np.array(DF_hk['score'])
hj_arr=np.array(DF_hj['score'])
panda_arr=panda_arr.reshape(-1,1)
hk_arr=hk_arr.reshape(-1,1)
hj_arr=hj_arr.reshape(-1,1)

In [11]:
hoho_scaled=scaler.transform(hoho_arr)
hoho_score=hoho_scaled*100
hoho_score=hoho_score.reshape(-1)
hoho_score=hoho_score.tolist()
hoho['final_score']=hoho_score

In [ ]:
panda_scaled=scaler.transform(panda_arr)
panda_score=panda_scaled*100
panda_score=panda_score.reshape(-1)
panda_score=panda_score.tolist()

hk_scaled=scaler.transform(hk_arr)
hk_score=hk_scaled*100
hk_score=hk_score.reshape(-1)
hk_score=hk_score.tolist()

hj_scaled=scaler.transform(hj_arr)
hj_score=hj_scaled*100
hj_score=hj_score.reshape(-1)
hj_score=hj_score.tolist()

In [ ]:
DF_panda['final_score']=panda_score
DF_hk['final_score']=hk_score
DF_hj['final_score']=hj_score

<ipython-input-165-28cc4302c124>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF_panda['final_score']=panda_score
<ipython-input-165-28cc4302c124>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF_hk['final_score']=hk_score
<ipython-input-165-28cc4302c124>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF_hj['final_score']=hj_score

In [12]:
hoho

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,0,1,2,senti,score,final_score
0,0,0,0,한옥집 마당에 앉아서 기다리다가 자리가 나서 안으로 들어가서 맛있는 식사를 했어요\...,"I was waiting in the yard of the hanok house, ...",11.0,pos,8.0,100.0
1,1,1,1,항상 대기가 많아보여서 엄두를 못 냈는데 생각보다 웨이팅도 빨리 빠지고 회전율이 빨...,It always looked like there was a lot of waiti...,11.0,pos,8.0,100.0
2,2,2,2,"혜화 주민이라 자주갔는데,혜화에서 약속잡기 좋은 식당이라고 생각합니다. 생각보다 마...",I went there often because I'm a resident of H...,27.0,pos,8.0,100.0
3,3,3,3,주중인데도 웨이팅있을만큼 인기있는 곳 매장 직원들이 친절하고 음식 맛도 좋아용!! ...,The store staff is so popular that they can wa...,7.0,pos,7.0,87.5
4,4,4,4,혜화에 방문한다면 젤 추천하고 싶은 밥집이에여! 친절하고 예쁘고 오픈시간부터 우르르...,"If you visit Hyehwa, it's a restaurant that I ...",11.0,pos,8.0,100.0
...,...,...,...,...,...,...,...,...,...
1743,1743,123,18,한옥에서 맛보는 일식^.^ 위장이 큰 사람에겐 조금 아쉬울 수 있어요!원래 찜마니 ...,Japanese food you can taste in Hanok.^ It can ...,32.0,pos,8.0,100.0
1744,1744,124,19,맛있어요 분위기도 괜찮고 새로만들어서 깔끔합니다. 분위기랑 맛 대비 가성비도 굳.,"It's good. The atmosphere is good, and it's cl...",12.0,pos,8.0,100.0
1745,1745,125,20,"대학로 소나무길에 새로 생긴 일본 가정식 ""호호식당"". 누가 성균관대 맛집을 물어본...","The new Japanese home-style ""Ho Ho Restaurant""...",44.0,pos,8.0,100.0
1746,1746,126,21,우선 예쁘니까 반절은 먹고 들어가는 곳사케동이고 뭐고 다 맛 보다 그 분위기에 취해...,"Since it's pretty, I think half of it tastes b...",1.0,pos,1.0,12.5
1747,1747,127,22,Absolutely love this beautiful restaurant. Set...,Absolutely love this beautiful restaurant. Set...,11.0,pos,8.0,100.0

In [ ]:
mean_panda=DF_panda['final_score'].mean()
mean_panda

40.270448548812666

In [ ]:
mean_hk=DF_hk['final_score'].mean()
mean_hk

59.59409594095941

In [ ]:
mean_hj=DF_hj['final_score'].mean()
mean_hj

47.57751937984496

In [13]:
mean_hoho=hoho['final_score'].mean()
mean_hoho

48.99885583524028

In [14]:
# DF_panda.to_csv('panda_mara_scored.csv') 
# DF_hk.to_csv('hk_mara_scored.csv') 
hoho.to_csv('hoho_scored.csv')